import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Config } from "@/lib/config";
import { NavbarTop } from "../components/navbar";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Guayaba Devs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg antialiased mx-auto overflow-auto",
          fontSans.variable
        )}>
        <Config>
          <NavbarTop />
          {children}
        </Config>
      </body>
    </html>
  );
}
